### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [novergeme/GTM-template-tag-vk-pixel-retarget-demo#2]
https://github.com/novergeme/GTM-template-tag-vk-pixel-retarget-demo/blob/4ffbdcfa9f8854e37173408e35b3e7e1c925b668/template.tpl#L900

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by novergeme** [comment]
Hi, thanks! It seems I used this function in the code in one place, then double-checked the result, the result is correct for sending the request. The only problem I have is that whatever I do GTM does not publish my template in the GTM template gallery. P.S. I followed all the rules, redid it 100 times, but it didn’t work, if you can help with this, I would be grateful, thanks!

**Comment by semisight** [comment]
So all you need to do is add

```javascript
const encodeUriComponent =  require('encodeUriComponent');
```

At the top of the sandboxed JS, and then for lines 900-905, change the lines to look like:

```javascript
var metaTagUrl = "&metatag_url=" + encodeUriComponent(data.metatagURL);
```

Basically, parameters need to be encoded before you put them into the request URL.

After this is addressed, we can approve your template and land it in the gallery.

**Comment by novergeme** [comment]
I added EncodeUriComponent() according to your requirements specification. Thank you very much! I will be very happy if my template appears in the GTM template gallery!

**Comment by novergeme** [comment]
@semisight Hello, I have applied the changes. It's been a week already but my template didn't show up in the template gallery in GTM. Please give feedback. What else can I do?

**Comment by semisight** [comment]
Hello @novergeme, I'm sorry for leaving this for so long. Your template has been approved and will show up in gallery shortly.
